from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Dict, Iterable, List, Set, Tuple
import hashlib

DIGIT_STRING = "182764125"
CHALLENGE_NUMBER = 7
TRUTH_LABEL = "CERTIFIED_FINITE_EXACT_INTEGER_RESULT_UNDER_STATED_RULES"

EXPECTED = {
    "possible_cut_patterns": 256,
    "unique_integer_values_generated": 99389,
    "positive_integer_values_generated": 53598,
    "non_positive_integer_values_generated": 45791,
    "negative_integer_values_generated": 45790,
    "zero_present": True,
    "consecutive_positive_integers_from_1": 4771,
    "first_missing_positive_integer": 4772,
    "minimum_integer_value": -82764124,
    "maximum_integer_value": 182764125,
    "all_interval_unique_values_generated": 102815,
    "boundary_witness_value": 4771,
    "boundary_witness_expression": "(1+((8+2)*(7+((6+41)*(2*5)))))",
}

EXPECTED_HASHES = {
    "all_values_sorted.txt": "b6cf7a413a9ba8bd212a6be91beeb499760ebde789085e06b3c7464ee4dca065",
    "positive_values_sorted.txt": "c2e849f48da9e3921de23c3dd2a0a19e384bbd4b0702b5a55f8fe05587a97dc5",
    "nonpositive_values_sorted.txt": "1395443d3c9fbe88e2625a0f25b8a52734b95f56b4d80feb3221618e4a83ffbb",
    "negative_values_sorted.txt": "cff3efe69cac42671b697ba2b4839e055ecd9f6c187648f00ff8fad370ef1924",
    "all_interval_values_sorted.txt": "1fb757597b9d916a2c4d533f0533830c9ace4d7c1d6edb9fbb5719ffcb787b96",
    "witnesses_1_to_4771.tsv": "542d5e6c6e0b2d9cd7d5981a1228b5127de693330fd4f4ea6e857ef87a00ca6b",
}


@lru_cache(maxsize=None)
def interval_values(i: int, j: int) -> frozenset[int]:
    """Return all values generated by the fixed ordered interval DIGIT_STRING[i:j]."""
    if not (0 <= i < j <= len(DIGIT_STRING)):
        raise ValueError(f"invalid interval [{i}, {j})")

    values: Set[int] = {int(DIGIT_STRING[i:j])}

    for k in range(i + 1, j):
        left = interval_values(i, k)
        right = interval_values(k, j)
        for a in left:
            for b in right:
                values.add(a + b)
                values.add(a - b)  # directional subtraction only
                values.add(a * b)

    return frozenset(values)


@lru_cache(maxsize=None)
def interval_witnesses(i: int, j: int) -> Dict[int, str]:
    """Return one expression witness for each generated value on an interval."""
    if not (0 <= i < j <= len(DIGIT_STRING)):
        raise ValueError(f"invalid interval [{i}, {j})")

    witnesses: Dict[int, str] = {int(DIGIT_STRING[i:j]): DIGIT_STRING[i:j]}

    for k in range(i + 1, j):
        left = interval_witnesses(i, k)
        right = interval_witnesses(k, j)
        for a, ea in left.items():
            for b, eb in right.items():
                candidates = (
                    (a + b, f"({ea}+{eb})"),
                    (a - b, f"({ea}-{eb})"),
                    (a * b, f"({ea}*{eb})"),
                )
                for value, expr in candidates:
                    witnesses.setdefault(value, expr)

    return witnesses


def full_values() -> frozenset[int]:
    return interval_values(0, len(DIGIT_STRING))


def full_witnesses() -> Dict[int, str]:
    return interval_witnesses(0, len(DIGIT_STRING))


def all_interval_values() -> frozenset[int]:
    universe: Set[int] = set()
    for i in range(len(DIGIT_STRING)):
        for j in range(i + 1, len(DIGIT_STRING) + 1):
            universe.update(interval_values(i, j))
    return frozenset(universe)


def consecutive_frontier(values: Iterable[int]) -> Tuple[int, int]:
    values_set = set(values)
    n = 1
    while n in values_set:
        n += 1
    return n - 1, n


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def integer_lines(values: Iterable[int]) -> str:
    return "".join(f"{x}\n" for x in sorted(values))


def compute_summary() -> dict:
    values = full_values()
    positives = {x for x in values if x > 0}
    nonpositives = {x for x in values if x <= 0}
    negatives = {x for x in values if x < 0}
    frontier, missing = consecutive_frontier(values)
    interval_universe = all_interval_values()
    max_abs = max(abs(min(values)), abs(max(values)))

    return {
        "possible_cut_patterns": 2 ** (len(DIGIT_STRING) - 1),
        "unique_integer_values_generated": len(values),
        "positive_integer_values_generated": len(positives),
        "non_positive_integer_values_generated": len(nonpositives),
        "negative_integer_values_generated": len(negatives),
        "zero_present": 0 in values,
        "consecutive_positive_integers_from_1": frontier,
        "first_missing_positive_integer": missing,
        "minimum_integer_value": min(values),
        "maximum_integer_value": max(values),
        "all_interval_unique_values_generated": len(interval_universe),
        "maximum_absolute_final_value": max_abs,
        "maximum_absolute_final_value_bit_length": max_abs.bit_length(),
        "boundary_witness_value": frontier,
        "boundary_witness_expression": full_witnesses()[frontier],
    }


def assert_expected_summary() -> dict:
    summary = compute_summary()
    for key, expected in EXPECTED.items():
        actual = summary.get(key)
        if actual != expected:
            raise AssertionError(f"{key}: expected {expected!r}, got {actual!r}")
    return summary
